export const GET_CONTENT = "GET_CONTENT";
export const GET_SUPPORTED_LOCALES = "GET_SUPPORTED_LOCALES";
export const GET_ALL_OBJECTS = "GET_ALL_OBJECTS";
export const GET_OBJECT_BY_ID = "GET_OBJECT_BY_ID";
export const ADD_OBJECT = "ADD_OBJECT";
export const UPDATE_OBJECT = "UPDATE_OBJECT";
export const DELETE_OBJECT = "DELETE_OBJECT";

export const SET_DRIVE_LINKS_NUMBER = "SET_DRIVE_LINKS_NUMBER";

export const RESET_ALL_ERRORS = "RESET_ALL_ERRORS";
export const RESET_ALL_INPUTS = "RESET_ALL_INPUTS";
export const SET_INPUT_VALUE = "SET_INPUT_VALUE";
export const GET_OBJECT_BY_ID_ERRORS = "GET_OBJECT_BY_ID_ERRORS";
export const VALIDATION_ERRORS = "VALIDATION_ERRORS";
export const GENERAL_ERRORS = "GENERAL_ERRORS";

export const SET_LOADING = "SET_LOADING";
export const SET_LOADING_FALSE = "SET_LOADING_FALSE";

export const SET_OBJECTS_FILTER_MODE = "SET_OBJECTS_FILTER_MODE";
export const SEARCH = "SEARCH";


// CMS
export const GET_FOOTER_CONTENT = "GET_FOOTER_CONTENT";

// Accounts
export const SET_AUTH = "SET_AUTH";
export const GET_ADMIN = "GET_ADMIN";
export const GET_CURRENT_LANG = "GET_CURRENT_LANG";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";


// Notifications
export const GET_ALL_NOTIFICATIONS = "GET_ALL_NOTIFICATIONS";

// Alert
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";



// Geofences
export const GET_ALL_GEOFENCES_MATCHING_DATA = "GET_ALL_GEOFENCES_MATCHING_DATA";
export const GET_ALL_MODELS = "GET_ALL_MODELS";
export const SET_POINTS_NUMBER = "SET_POINTS_NUMBER";
export const SET_SERVICES_NUMBER = "SET_SERVICES_NUMBER";

// Actions
export const GET_ALL_GEOFENCE_TYPES = "GET_ALL_GEOFENCE_TYPES";

// Users

// IoT Devices
export const GET_ALL_IOT_GEOFENCES = "GET_ALL_IOT_GEOFENCES";
export const GET_ALL_AVAILABLE_IOT_DEVICES = "GET_ALL_AVAILABLE_IOT_DEVICES";

// Scenarios
export const GET_ALL_SCENARIOS_DATA = "GET_ALL_SCENARIOS_DATA";